### ISSUE TITLE
Failed to interpret file 'IAN_simple.npz' as a pickle

### ISSUE THREAD

**Issue by abrahamyan-lusine** [ajbrock/Neural-Photo-Editor#12]
I just want to run NPE.py file, but it cant load weights

**Comment by ajbrock** [comment]
Hmm, it looks like git-LFS has a bandwidth limit that's been exceeded. Here's a drive mirror: https://drive.google.com/open?id=0B3_iVBZsC4GGck5WWWc0R0dvT1U

**Comment by abrahamyan-lusine** [comment]
Cool thanks!
