### ISSUE TITLE
IDEA: Option to save changed image as the new ground-truth image

### ISSUE THREAD

**Issue by michaelrgb** [ajbrock/Neural-Photo-Editor#7]
I was trying to make multiple independent changes to an image and I came to the following conclusion:

The masking technique means the output image is based off the original
ground-truth image. After an aesthetically pleasing change is made, such as
growing the length of the hair, a new ground-truth image must be saved and
the latent space recalculated **before** a different change is made such as
changing the hair color.

By adding the following PR I was able to get these results:
https://github.com/ajbrock/Neural-Photo-Editor/pull/8

Original image:
![original](https://cloud.githubusercontent.com/assets/20949168/18926840/486f80e4-85b1-11e6-978c-9a52e53c46cd.png)

First operation - increase hair length:
![longerhair](https://cloud.githubusercontent.com/assets/20949168/18926866/5ba139fa-85b1-11e6-85c4-6d741e2ae8e0.png)

Second operation AFTER saving the new ground-truth image - new hair color:
![newhaircolor](https://cloud.githubusercontent.com/assets/20949168/18926894/6bbae37c-85b1-11e6-8174-068847832478.png)

Without saving the new ground-truth image, I was unable to get these results as the algorithm attempted to remove my longer black hair when I attempted to change it to yellow, because it matches the skin color.

**Comment by ajbrock** [comment]
I like the idea--want to make this a pull request? I'll take a look at it and likely integrate it in as an option. It's starting to look like there's going to be a fairly large number of buttons, so I'm considering looking into a menu or dropdown menu of some sort.

**Comment by michaelrgb** [comment]
Thanks, linked to a PR.

**Comment by ajbrock** [comment]
PR accepted. Thanks for the add, great idea! I changed the button name to "Update," which I now realize may be a bit confusing what with "Reset" and "Infer" already being there (with "Reset" returning to the current ground truth and "Infer" re-inferring from an original image), so I'll take a look into coming up with better names soon.
